---
- hosts: all
  become: yes
  tasks:
    - name: Ensure NTP is installed.
      apt: name=ntp state=present
    - name: Reload systemd
      systemd: daemon_reload=yes
    - name: Ensure NTP is running.
      service: name=ntp state=started enabled=yes

